config/routes.rb
Rails.application.routes.draw do
 resources :kittens 
 root "kittens#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def index
    @kittens = Kitten.all
    respond_to do |format|
      format.json {render :json => @kittens }
    end
  end

  def show
    @kitten = Kitten.find(params[:id])
  end

  def new
    @kitten = Kitten.new
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def create
    @kitten = Kitten.create(kitten_params)
    if @kitten.save
      flash.notice = "Congrats! You just saved a new Kitten!"
      redirect_to root_path
    else
      flash.notice = "Oh no! Kitten was not saved, try again"
      redirect_to new_kitten_path
    end
  end

  def update
    @kitten = Kitten.find(params[:id])
    if @kitten.update(kitten_params)
      redirect_to @kitten
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @kitten = Kitten.find(params[:id])
    @kitten.destroy
    redirect_to root_path

  end


  private

    def kitten_params
      params.require(:kitten).permit(:name, :age, :cuteness, :softness)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_with model: @kitten do |form| %>
  <div class="col-sm-3">
      <%= form.label :name %><br />
      <%= form.text_field :name, class: "form-control" %>
  </div>
  <div class="col-sm-3">
      <%= form.label :age %><br />
      <%= form.number_field :age, class: "form-control" %>
      <br>
  </div>
  <div class="col-sm-3">
      <%= form.label :cuteness %><br />
      <%= form.number_field :cuteness, class: "form-control" %>
      <br>
  </div>
  <div class="col-sm-3">
      <%= form.label :softness %><br />
      <%= form.number_field :softness, class: "form-control" %>
      <br>
  </div>
 
  <div >
        <%= form.submit "Submit", class: "btn btn-primary btn-lg" %>
    </div>
    <br>
     <div >
        <%= link_to "Cancel", kittens_path, class: "btn btn-secondary" %>
    </div>
<% end %>

app/views/kittens/create.html.erb
<h1>Kittens#create</h1>
<p>Find me in app/views/kittens/create.html.erb</p>

app/views/kittens/edit.html.erb
<h1>Edit <%=@kitten.name%>'s profile</h1>
  
  <%= render "kittens/form", kitten: @kitten %>
  

app/views/kittens/index.html.erb
<h1>Kittens API</h1>
<div>
  <p>Here are all your kittens: </p>
</div>
<table class="table table-striped">
   <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Age</th>
      <th scope="col">Cuteness</th>
      <th scope="col">Softness</th>
      
    </tr>
  </thead>
  <tbody>
    <% @kittens.each do |kitten| %>
    <tr>
      <td style="width:12%"> <%=kitten.name%> </td>
      <td style="width:12%"><%= kitten.age %> </td>
      <td style="width:12%"><%= kitten.cuteness %> </td>
      <td style="width:12%"><%= kitten.softness %> </td>
      <td style="width:12%"><%= link_to "Profile", kitten, class: "btn btn-success" %></td>
    <% end %>
  </tbody>
  
</table>

app/views/kittens/new.html.erb
<h1>Add new Kitten! </h1>
<%= render "kittens/form" %>
  

app/views/kittens/show.html.erb
<h1><%=@kitten.name%></h1>

<table class="table table-striped">
   <thead>
    <tr>
      <th scope="col">Age</th>
      <th scope="col">Cuteness</th>
      <th scope="col">Softness</th>
      
    </tr>
  </thead>
  <tbody>
  
    <tr>
      <td ><%= @kitten.age %> </td>
      <td ><%= @kitten.cuteness%> </td>
      <td ><%= @kitten.softness %> </td>
      <td ><%= link_to "Edit", edit_kitten_path, class: "btn btn-info"%>
     

  </tbody>

  
</table>

<%= button_to "Destroy", @kitten, method: :delete, class: "btn btn-danger"  %>

app/views/kittens/update.html.erb
<h1>Kittens#update</h1>
<p>Find me in app/views/kittens/update.html.erb</p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
  <div class="container-fluid">
    <%= link_to 'Kittens',
    root_path, class: "navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Add New Kitten',
          new_kitten_path, class: "nav-link active"%>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Odins Kittens</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  </head>
  <body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <%= render "layouts/navbar"%>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      </br>
      <%= yield %>
    </div>
  </body>
</html>